### ISSUE TITLE
Array index out of range

### ISSUE THREAD

**Issue by gavnamu** [ctrl-alt-dev/tps-parse#6]
Array index out of range: 1065634308 how can I increase the array index when the file to be extracted is very big

**Comment by vinnygambiny** [comment]
I have the same error, do you have find a workaround ?

**Comment by ctrl-alt-dev** [comment]
Can you provide the output of the tool and the stacktrace (-e option)?

**Comment by vinnygambiny** [comment]
```
Incomplete Page
REMINDER.TPS : Array index out of range: 1540
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 1540
	at nl.cad.tpsparse.bin.RandomAccess.checkSpace(RandomAccess.java:94)
	at nl.cad.tpsparse.bin.RandomAccess.leLong(RandomAccess.java:81)
	at nl.cad.tpsparse.tps.TpsBlock.isCompletePage(TpsBlock.java:124)
	at nl.cad.tpsparse.tps.TpsBlock.<init>(TpsBlock.java:54)
	at nl.cad.tpsparse.tps.TpsFile.getTpsBlocks(TpsFile.java:214)
	at nl.cad.tpsparse.tps.TpsFile.visit(TpsFile.java:236)
	at nl.cad.tpsparse.tps.TpsFile.getTableDefinitions(TpsFile.java:439)
	at nl.cad.tpsparse.Main.parseFile(Main.java:169)
	at nl.cad.tpsparse.Main.main(Main.java:122)
```

**Comment by ctrl-alt-dev** [comment]
This happens when an incomplete, bad or misunderstood page is encountered in the tps file. You can skip these using `-ignoreErrors`. The information in those pages is not converted.
