### ISSUE TITLE
Password not valid or other error

### ISSUE THREAD

**Issue by vinnygambiny** [ctrl-alt-dev/tps-parse#9]
Hi, I have the encrypted error. I have set the password, but not sure that is the good password. Not all file are encrypted.

```
java -jar tps-to-csv.jar -s ./240529data -t ./240529data_csv -e -password "_&$#"

Encrypted file, using set password.
Exception in thread "main" nl.cad.tpsparse.tps.NotATopSpeedFileException: File doesn't start with 0x00000000 - its not a TopSpeed file or it may be 'encrypted'.
	at nl.cad.tpsparse.tps.TpsHeader.<init>(TpsHeader.java:50)
	at nl.cad.tpsparse.tps.TpsFile.getHeader(TpsFile.java:191)
	at nl.cad.tpsparse.tps.TpsFile.<init>(TpsFile.java:155)
	at nl.cad.tpsparse.tps.TpsFile.<init>(TpsFile.java:116)
	at nl.cad.tpsparse.Main.openFile(Main.java:298)
	at nl.cad.tpsparse.Main.parseFile(Main.java:166)
	at nl.cad.tpsparse.Main.main(Main.java:132)
```

**Comment by vinnygambiny** [comment]
I can confirm, it's the good password. I have try with  `-password "_&$#"` and `-password _\&$#` and it's don't work. I can't change the password... They have a way to use this password ?

**Comment by ctrl-alt-dev** [comment]
For a TPS file to be valid in this software the first 4 bytes need to be zero (it is the absolute position in the file; the start, so 0). 
If the value is different, it can mean the following: 
- the file is encrypted, you provided no password
- the file is encrypted, you provided a password, but it didn't decrypt the start to 0s, so the password is incorrect.
- the file is not a TPS file.

Some suggestions:
- How do you know the password is correct? 
- It looks like you're converting a folder; did you try the files one by one?

**Comment by vinnygambiny** [comment]
Yes I have run on folder, then on one file. The password work for the software that use the DB.

**Comment by ctrl-alt-dev** [comment]
Sometimes the password of the software is not the same as that for the DB unfortunately.

**Comment by vinnygambiny** [comment]
[cfg.tps.zip](https://github.com/user-attachments/files/15894358/cfg.tps.zip)
Here an exemple of a file I can't convert, if you can help me is appreciate.

**Comment by ctrl-alt-dev** [comment]
I ran some checks on the file. 
Normally block #15 of the key is recoverable, but for your file it isn't.
I don't think it is encrypted using the tps encryption algorithm but something else. 

Later versions of the clarion tps driver support [enhanced encryption](http://clarion.help/doku.php?id=enhanced_encryption_support_in_the_topspeed_driver.htm) - my guess is this is used.  
If that is the case your best bet is to contact the developer of your software for support.
